import type {FourtuneNodeAPIOptions, FourtuneConfig, FourtuneEvents} from "@fourtune-types/fourtune/v0"
import type {_EmitEventType} from "@aniojs/event-emitter"
import type {InternalState, FileToAutogenerate} from "#~src/InternalState.d.mts"
import path from "node:path"
import {scandir} from "@aniojs/node-fs"
import {scandirEntriesToInputFiles} from "./scandirEntriesToInputFiles.mts"
import {autogeneratedFilesToInputFiles} from "./autogeneratedFilesToInputFiles.mts"

export async function initialize(
	fourtuneOptions: Required<FourtuneNodeAPIOptions>,
	projectRoot: string,
	projectConfig: FourtuneConfig,
	_emitEvent: _EmitEventType<FourtuneEvents>
) : Promise<InternalState> {
	const rawSourceFiles = await scandir(
		path.join(projectRoot, "src")
	)

	const sourceFiles = scandirEntriesToInputFiles("src", rawSourceFiles)

	const rawAssetFiles = await scandir(
		path.join(projectRoot, "assets"), {
			allow_missing_dir: true
		}
	)

	const assetFiles = scandirEntriesToInputFiles("assets", rawAssetFiles)

	const filesToAutogenerate : FileToAutogenerate[] = []

	for (const key in projectConfig.autogenerate) {
		const generator = projectConfig.autogenerate[key]

		filesToAutogenerate.push({
			filePath: key,
			category: "user",
			generator
		})
	}

	return {
		project: {
			root: projectRoot,
			config: projectConfig
		},

		rawInput: {
			sourceFiles: rawSourceFiles,
			assetFiles: rawAssetFiles
		},

		input: {
			sourceFiles: [
				...autogeneratedFilesToInputFiles(
					filesToAutogenerate,
					"fourtune/src"
				),
				...autogeneratedFilesToInputFiles(
					filesToAutogenerate,
					"synthetic/async.sync/src"
				),
				...autogeneratedFilesToInputFiles(
					filesToAutogenerate,
					"synthetic/user/src"
				),
				...sourceFiles
			],

			assetFiles: [
				...autogeneratedFilesToInputFiles(
					filesToAutogenerate,
					"assets/"
				),
				...assetFiles
			]
		},

		filesToAutogenerate,

		_emitEvent
	}
}
